osx_image: xcode11.4
language: swift
script:
- set -o pipefail && xcodebuild -workspace Example/SheetKit.xcworkspace -scheme SheetKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
